### ISSUE TITLE
tarod v0.1.1-alpha Not Launching Ubuntu 20.04 Bitcoin Core 24.99 LND 0.15.4 Testnet

### ISSUE THREAD

**Issue by D33r-Gee** [lightninglabs/taro#209]
**Expected behavior**
Followed the video tutorial here:
https://youtu.be/xtklaJHfKIY
And the instructions here:
https://github.com/lightninglabs/taro

Once I launch tarod I expected it to connect to the testnet running on the same machine

**Actual behavior**

When launching using:
`tarod --network=testnet --debuglevel=debug --lnd.host=localhost:10009 --lnd.macaroonpath=~/.lnd/data/chain/bitcoin/testnet/admin.macaroon --lnd.tlspath=.lnd/tls.cert`

The output is 

```
2022-11-30 11:39:57.567 [WRN] CONF: open /home/opb/.taro/taro.conf: no such file or directory
2022-11-30 11:39:57.568 [INF] CONF: Opening sqlite3 database at: /home/opb/.taro/data/testnet/taro.db
2022-11-30 11:39:58.528 [INF] CONF: Attempting to establish connection to lnd...
error creating server: unable to connect to lnd node: error checking connected lnd version. at least version "v0.15.99, build tags 'signrpc,walletrpc,chainrpc,invoicesrpc'" is required
```

**To reproduce**

Running the lnd version 0.15.4-beta `make && make install tags=”signrpc walletrpc routerrpc invoicesrpc”`

The lnd and lncli do compile then running` lnd –network=testnet getinfo`
returns:
"version": "0.15.4-beta commit=v0.15.4-beta"...
"testnet": true
"chains": [
        {
            "chain": "bitcoin",
            "network": "testnet"
        }
    ]

**System information**

Using Bitcoin Core version 249900

Ubuntu 20.04 

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
Model name:                      Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Disk type: sda

**Comment by guggero** [comment]
You need `lnd` at commit `ca501d92` (that exact version, everything later on the `master` branch is broken and only fixed by #206). Do `git checkout ca501d92 && make && make install tags="signrpc walletrpc routerrpc invoicesrpc"`

**Comment by D33r-Gee** [comment]
@guggero thanks for the prompt response.

> Do `git checkout ca501d92 && make && make install tags="signrpc walletrpc routerrpc invoicesrpc"`

updated lnd it is now  `"version": "0.15.99-beta commit=cert/v1.2.0-119-gca501d920"` as you instructed however still getting that same error from inputting 

`tarod --network=testnet --debuglevel=debug --lnd.host=localhost:10009 --lnd.macaroonpath=~/.lnd/data/chain/bitcoin/testnet/admin.macaroon --lnd.tlspath=.lnd/tls.cert`

```
2022-11-30 15:44:24.185 [WRN] CONF: open /home/opb/.taro/taro.conf: no such file or directory
2022-11-30 15:44:24.186 [INF] CONF: Opening sqlite3 database at: /home/opb/.taro/data/testnet/taro.db
2022-11-30 15:44:24.190 [INF] CONF: Attempting to establish connection to lnd...
error creating server: unable to connect to lnd node: error checking connected lnd version. at least version "v0.15.99, build tags 'signrpc,walletrpc,chainrpc,invoicesrpc'" is required
```
Does the lnd node need to have open channels for Taro to work/connect?

**Comment by guggero** [comment]
Ah, I just copy pasted your command but according to the error message you also need to add the chainrpc build tag.
No channel required but on-chain funds in lnd's wallet.

**Comment by D33r-Gee** [comment]
SUCCESS!

Thanks @guggero!

Now gonna make some "Magic Internet Money" ;)
